app_name: bankrupt-officer-search-web
group: web
weight: 991
# When we move static files to the CDN routes 3, and 4 will be removed
routes:
  1: /admin/officer-search/scottish-bankrupt-officer
  2: /admin/officer-search/scottish-bankrupt-officer/.*